"""added models

Revision ID: 015b93ddc5db
Revises: 
Create Date: 2023-08-18 17:49:40.863675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015b93ddc5db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrases_description'), 'phrases', ['description'], unique=False)
    op.create_index(op.f('ix_phrases_id'), 'phrases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrases_id'), table_name='phrases')
    op.drop_index(op.f('ix_phrases_description'), table_name='phrases')
    op.drop_table('phrases')
    # ### end Alembic commands ###
